### ISSUE TITLE
Can returned value be left value?

### ISSUE THREAD

**Issue by XOR-op** [ACMClassCourses/Compiler-Design-Implementation#2]
According to 8.3, the grammar of accessing a member is `<ClassObjectIdentifier>.<ClassMember>;` OR `<ClassObjectIdentifier>.<ClassMethod>(<FunctionParameterList>`. Is the following code valid or undefined?
```c++
class A{
    A self(){return this;}
    int v;
}
int main(){
    A a;
    a.self().self().v=3;
    return 0;
}
```
Or the members can only accessed directly with identifier?

**Comment by ZYHowell** [comment]
The answer to the first question is invalid, but the answer to the second is complex. 
Read section 8.3 for more details.
