### ISSUE TITLE
Yx/testcases/correct.yx syntax error

### ISSUE THREAD

**Issue by SiriusNEO** [ACMClassCourses/Compiler-Design-Implementation#5]
```
struct A {
    int a;
}  // missing ; here ?
int main(){
...
```

**Comment by peterzheng98** [comment]
Yx language has different syntax.

**Comment by SiriusNEO** [comment]
But the Yx compiler throws a syntax error here
![image](https://user-images.githubusercontent.com/41781658/134479389-39feb3d3-2a9e-4a33-a539-4272ccb4d3d9.png)
